server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: fretes
          predicates:
            - Path=/**
          uri: lb://fretes



#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        boot:
#          autoconfigure:
#            web: debug
#        cloud:
#          gateway: debug
#        http:
#          server:
#            reactive: debug
#        web:
#          reactive: debug
#reactor:
#  netty: debug
#redisratelimiter: debug



