
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: fretes
          uri: lb://fretes
          predicates:
            - Path=/new-account
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-img:8081/eureka/
    fetch-registry: true
    register-with-eureka: true